### ISSUE TITLE
Add the possibility to pass an array to all `keyValue` actions

### ISSUE THREAD

**Issue by EmrysMyrddin** [alakarteio/k-redux-factory#103]
## Problem
We often have to update every values in a `keyValue` store. But with the current API, it can lead to a huge number of dispatched actions.

## Proposition
I propose to make `update`, `addOrUpdate` and `replace` action polymorphic on their argument, allowing to pass an instance or an array of instances.

## Example
```es6
import { keyValue } from 'k-redux-factory'

const store = keyValue({ key: 'id' })

store.addOrUpdate([
  { id: 1, value: '1' },
  { id: 2, value: '2' },
  { id: 3, value: '3' },
])
```

**Comment by fabienjuif** [comment]
This is a nice catch.

And as you said in your PR, we will maybe hit a performance issue.
That's why I opened #108 .

Can you review this PR, and next steps associated. I would like to know your opinion about this.
