### ISSUE TITLE
Add a default key for `keyValue`

### ISSUE THREAD

**Issue by EmrysMyrddin** [alakarteio/k-redux-factory#104]
The key for a `kyeValue` store is very often `id`. We can perhaps set this as default `key` ?

**Comment by fabienjuif** [comment]
I think we can.

The main purpose was to not hide the kind of parameter.
So people don't feel obliged to use `id` as value and **know** there is `key` parameter.

**Comment by fabienjuif** [comment]
@EmrysMyrddin what is your opinion about this ?

ping @bpetetot  / @guillaumecrespel

**Comment by EmrysMyrddin** [comment]
I understand the idea. I think we should ask the question to someone not confident with our API.
