### ISSUE TITLE
remove with instance object

### ISSUE THREAD

**Issue by fabienjuif** [alakarteio/k-redux-factory#118]
Right now we can remove instance from `keyValue` per their `key`.
Add the possibility to remove them per reference equality to full instance.

pseudo code:
```js
const = remove = ([object]) => {
  if (typeof object === 'object') {
    // remove per reference equality
  } else {
    // remove per id 
  }
}
```

**Comment by guillaumecrespel** [comment]
use object reference ? or test `key` for each object ?

**Comment by fabienjuif** [comment]
We already test key.
Then add the usage of reference.
