### ISSUE TITLE
Version 6.0.0

### ISSUE THREAD

**Issue by fabienjuif** [alakarteio/k-redux-factory#128]
Hey @bpetetot @EmrysMyrddin @FRINYvonnick !

I would like to publish the stable release `6.0.0`.
Are you ok with this release ?

The changes ares theses commits: https://github.com/alakarteio/k-redux-factory/compare/4224d847d3678347f507814d9c270160cd7f2c84...master

There is a `rc` published with the `next` tag: `yarn add k-redux-factory@next`.
If you can test this new version on one of your own project it could be great :) 

Thank to all of you.

--- 

I put a deadline to the next week so I can move on if I have no response.

**Comment by fabienjuif** [comment]
There is some other information about this version here: https://github.com/alakarteio/k-redux-factory/milestone/1?closed=1

**Comment by frinyvonnick** [comment]
Hi, 

I experienced some issues using rc2. It seems that named export are missing in dist version.

I created a repositories with tests that reproduce my issues: https://github.com/frinyvonnick/test-k-redux-factory-6

Any ideas ?

**Comment by fabienjuif** [comment]
Can you try the `rc3` ?
https://www.npmjs.com/package/k-redux-factory/v/6.0.0-rc3

I can try this myself tomorrow :)

**Comment by fabienjuif** [comment]
This is same error with rc3, I think this is the UMD build that sucks :(
The es build seems fine.

I will not mix default and named exports, and I will move `factory` to a named export

**Comment by fabienjuif** [comment]
I juste published `6.0.0-rc5` 

@frinyvonnick

**Comment by fabienjuif** [comment]
I tested it in our client project and it works fine.
I am not 100% sure about perf but whatever.

To test it I also updated k-ramel if you are interested :)

![image](https://user-images.githubusercontent.com/17828231/42652339-66fdcce2-8612-11e8-8c57-49f650180744.png)

**Comment by fabienjuif** [comment]
Thank you guys :)
