### ISSUE TITLE
Use path instead of prefix to differentiate two reducers with same name

### ISSUE THREAD

**Issue by vmenard** [alakarteio/k-redux-factory#73]

**Comment by fabienjuif** [comment]
Hi!

We argued about that with @guillaumecrespel.

If we use something like this to describe actions: `@trampss/<PATH>/<ACTION>_<RESOURCE>`, it makes difficult to move your reducers from one path to an other : your event listener (redux-saga) will be dependent from your PATH, and I thank it was a drawback 

Can you tell us why you don't like `prefix` option solution? 
Maybe there is an other solution we can agree?

I prefer to dig a new solution, and if we can't find one, maybe we will add path to actions types

**Comment by fabienjuif** [comment]
@bpetetot @vmenard what is your point of view ?
I know both of you suggested the PATH prefix.

What do you think of my arguments ?

**Comment by vmenard** [comment]
I totally agree with you, but during my developments, I didn't know that prefix was required when you have the same name for a reducer. I haven't read the documentation :)
