### ISSUE TITLE
new selector: includes

### ISSUE THREAD

**Issue by fabienjuif** [alakarteio/k-redux-factory#82]
@bpetetot

**Comment by fabienjuif** [comment]
I am not sure anymore about this @bpetetot 
What was the purpose ?
This is a reference test ?

**Comment by bpetetot** [comment]
the purpose was to do `factory.includes(<instance>)(state)` but I dont think that necessary with the  new `hasKey`selector. Because you can do `factory.hasKey(<instance>.id)(state)`

**Comment by fabienjuif** [comment]
Ok we then agree.
I close this
