### ISSUE TITLE
what is the difference between add and replace code

### ISSUE THREAD

**Issue by fabienjuif** [alakarteio/k-redux-factory#86]

**Comment by fabienjuif** [comment]
- `add`: add an instance in every situation (and erase the old one if it exists)
 - `replace`: replace the old one if it exists. If no old instance exists, `replace` does nothing.

The question is: 
 - Why do we need a `replace` behaviour as described ?

ping @guillaumecrespel / @bpetetot / @EmrysMyrddin

---

I vote to remove `replace`.

**Comment by EmrysMyrddin** [comment]
I don't think I have ever used `replace`. I'm not able to find a real use case for this. I'm agree to remove it.
