### ISSUE TITLE
API / simpleObject / defaultValue

### ISSUE THREAD

**Issue by guillaumecrespel** [alakarteio/k-redux-factory#98]
What do you think to add the possibility to add defaultValue with the first parameter ?

|function|defaultValue|
|--|--|
|simpleObject()|{}|
|simpleObject({ defaultValue: {} })|{}|
|simpleObject({ my: 'object' })|{}|
|simpleObject('string')|'string'|
|simpleObject([1, 2, 3])|[1, 2, 3]|

**Comment by fabienjuif** [comment]
And what about 

simple.object
simple.string
simple.bool
simple....

**Comment by guillaumecrespel** [comment]
it makes it more complex the api no ?
But why not :)

**Comment by EmrysMyrddin** [comment]
The main problem I have with the current API is that `simpleObject` doesn't represent the fact that it can be any type of value.

**Comment by EmrysMyrddin** [comment]
After some reflection, I like @fabienjuif idea. It could allow to have a defaultData depending of the chosen type. And it also allow us to add some custom actions, `toggle` for boolean for example.
